  
version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7.29
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
